name: Z-Account Auto KeepAlive

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch: {}

jobs:
  run-z-account:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - run: pip install requests
      - name: Random Delay
        run: |
          if [ "${{ github.event_name }}" != "workflow_dispatch" ]; then
            WAIT_SEC=$((RANDOM % 3600))
            echo "Sleeping for ${WAIT_SEC} seconds"
            sleep $WAIT_SEC
          fi
      - name: Run Script
        env:
          GITHUB_REPO_NAME: ${{ github.repository }}
          CLIENT_ID: ${{ secrets.Z_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.Z_CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.Z_REFRESH_TOKEN }}
          TENANT_ID: ${{ secrets.Z_TENANT_ID }}
        run: python main.py
