name: X-Account KeepAlive
on:
  schedule:
    - cron: '30 2,8,14,20 * * *'
  workflow_dispatch: {}
concurrency:
  group: x-group
  cancel-in-progress: true
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install requests
      - shell: bash
        run: |
          [ "${{ github.event_name }}" == "workflow_dispatch" ] && exit 0
          sleep $((RANDOM % 2700))
      - env:
          GITHUB_REPO_NAME: ${{ github.repository }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          TENANT_ID: ${{ secrets.TENANT_ID }}
        run: python main.py
